meta:
  name: 'DKBansReportReward English'
  module: 'DKBansReportReward'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkbans.reportReward.reward: '&8» &6DKCoins &8|&f &a+&6{reward}$'
